version: '3.0'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 256M

  rabbit_mq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 512M

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 512M

  cookiecutter_fast_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: cookiecutter_fast_api
    ports:
      - "8000:8000"
    env_file:
      - docker-compose.env
    environment:
      - DEBUG=true
    volumes:
      - ./:/app
    depends_on:
      - redis
      - postgres
      - rabbit_mq

  cookiecutter_fast_api_worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: cookiecutter_fast_api
    command: celery -A cookiecutter_fastAPI.worker.celery_worker worker -l info
    env_file:
      - docker-compose.env
    environment:
      - DEBUG=true
    volumes:
      - ./:/app
    depends_on:
      - redis
      - postgres
      - rabbit_mq