version: '3.0'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 256M

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 256M

  cookiecutter_fast_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - docker-compose.env
    environment:
      - DEBUG=true
    volumes:
      - ./:/app
    depends_on:
      - redis
      - postgres

#  cookiecutter_fast_api_worker:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: celery worker *
#    env_file:
#      - docker-compose.env
#    environment:
#      - DEBUG=true
#    volumes:
#      - ./:/app
#    depends_on:
#      - redis
#      - postgres